config/routes.rb
Rails.application.routes.draw do

  root 'pictures#index'
  #
  resources :users do
    resources :pictures do
      resources :comments
    end
  end

  resources :sessions, only:[:new, :create]
  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy', as: :logout
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :picture
  has_many :pictures
  has_many :users
end

app/models/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :authorize #makes it globally accessible

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  def logged_in?
    !!current_user
  end
  def authorize
    redirect_to new_session_path unless logged_in?
  end
end

app/models/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/models/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
    @pictures = Picture.all
  end

  def new
    @picture = Picture.new
    @user = current_user
  end

  def create
    @picture = Picture.new(params.require(:picture).permit(:url, :caption, :tag))
    @picture.user = current_user #current_user is the one who's posting the pic. have to have this orelse Picture.new's user_id will be nil
    if @picture.save
      redirect_to user_path(current_user)
    else
      render :new #don't refresh the page, stay at the new/form page
    end
  end

  def show
  end

  def edit
    p params
    @picture = Picture.find(params[:id])
    @user = current_user
  end

  def update
    @picture = Picture.find(params[:id])
      if @picture.update_attributes(picture_params)
        redirect_to user_path(current_user)
      else
        redirect_to edit_user_path
      end
  end

  def destroy
    @user= current_user
    @picture = Picture.find(params[:id])
      if @picture.destroy
        redirect_to user_path(params[:user_id])
      else
        redirect_to edit_user_path(params[:user_id])
      end
  end


  def picture_params
    params.require(:picture).permit(:url, :caption, :tag)
  end
end

app/models/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    #first, try and find the user by email in the dv
    @user = User.find_by_email(params[:login][:email])
    #if the user exists and they put in the right password

    if @user && @user.authenticate(params[:login][:password])
      #generate a cookie for the user
      #redirect them somewhere
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      
      #redirect them back to the login page
      redirect_to login_path

  end
end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/models/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only: [:show]

  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params) #only  secure those three fields
    if @user.save
      redirect_to root_path

    else
      redirect_to new_user_path
    end
  end

  def edit
    @user = User.find params[:id] #when you edit the user already exists in the db
  end

  def update

    @user = User.find(params[:id])
      if @user.update_attributes(user_params)
        redirect_to user_path
      else
        redirect_to edit_user_path
      end
  end

  def destroy
    @user = User.find(params[:id])
      if @user.destroy
        # session[:user_id] #destroy current user id from this session
        redirect_to users_path #redirect to homepage, index
      else
        redirect_to edit_user_path #redirects to the same user, edit path
      end
    end

  private #only available here
  def user_params
    params.require(:user).permit(:name, :email, :tagline, :bio, :password, :pic_url)
  end
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_attached_file :url,
                    styles: {medium: "500x500#", thumb: "100x100#"},
                    storage: :s3,
                    url: ":s3_domain_url",
                    path: "/:class/:id_partition/:style/:filename",
                    s3_region: ENV["S3_REGION"],
                    s3_credentials: Proc.new{ |a| a.instance.s3_credentials }

def s3_credentials
  {
    bucket: ENV["S3_BUCKET_NAME"],
    access_key_id: ENV["S3_ACCESS_KEY_ID"],
    secret_access_key: ENV["S3_SECRET_ACCESS_KEY"]
  }
end

validates_attachment_content_type :url, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :pictures
  has_many :comments
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
    @pictures = Picture.all
  end

  def new
    @picture = Picture.new
    @user = current_user


  end

  def create
    @picture = Picture.new(params.require(:picture).permit(:url, :caption, :tag))
    @picture.user = current_user #current_user is the one who's posting the pic. have to have this orelse Picture.new's user_id will be nil
    if @picture.save
      redirect_to user_path(current_user)
    else
      render :new #don't refresh the page, stay at the new/form page
    end
  end

  def show
  end

  def edit
    p params
    @picture = Picture.find(params[:id])
    @user = current_user
  end

  def update
    @picture = Picture.find(params[:id])
      if @picture.update_attributes(picture_params)
        redirect_to user_path(current_user)
      else
        redirect_to edit_user_path
      end

  end

  def destroy
    @user= current_user
    @picture = Picture.find(params[:id])
      if @picture.destroy
        redirect_to user_path(params[:user_id])
      else
        redirect_to edit_user_path(params[:user_id])
      end
  end


  def picture_params
    params.require(:picture).permit(:url, :caption, :tag)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'VXH', root_path, {class: 'navbar-brand'} %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li><%= link_to user_path(current_user) do %>
          <%= current_user.name %>
          <span class="glyphicon glyphicon-user"></span>
          <% end %>
        </li>

        <li><%= link_to 'Log Out', logout_path, method: 'DELETE' %></li>
        <% else %>
        <li><%= link_to 'Sign Up', new_user_path %></li>
        <li><%= link_to 'Log In', login_path %></li>
        <% end %>

      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthenticationPractice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class= "container">
        <%= yield %>
    </div>


  



  </body>
</html>

app/views/pictures/create.html.erb
<h1>Pictures#create</h1>
<p>Find me in app/views/pictures/create.html.erb</p>

app/views/pictures/destroy.html.erb
<h1>Pictures#destroy</h1>
<p>Find me in app/views/pictures/destroy.html.erb</p>

app/views/pictures/edit.html.erb
<h1>Edit Memory</h1>
<!-- <p>Find me in app/views/pictures/edit.html.erb</p> -->
<div>
  <%= form_for [@user, @picture] do |f|%>
    <%= f.label :url, 'Upload photo' %>
    <%= f.file_field :url, placeholder: 'Upload Picture' %>
  <div id="div-space"></div>
    <%= f.label :caption, 'Caption' %>
  <div id="div-space2"></div>
    <%= f.text_field :caption, placeholder: 'Write a caption' %>
    <!-- <%= f.label :tag, 'tag' %>
    <%= f.text_field :tag, placeholder: 'Write a tag' %> -->
    <%= f.submit 'Create Post' %>
  <% end%>

</div>

app/views/pictures/index.html.erb
<h1 class="italic">Collective Collaboration</h1>
<!-- <p>Find me in app/views/pictures/index.html.erb</p> -->
<div class="middle">
<% @pictures.reverse.each do |p| %>
<div class="col-md-4">
  <%= image_tag(p.url) %>
  <h3 class="caption-style"><%= p.caption %></h3>
  <em><%= p.user.name %></em>
  <!-- <em><%= p.user.email %></em> -->
</div>
<% end %>
</div>

app/views/pictures/new.html.erb
<h1>Upload a memory</h1>
<h3>“A good snapshot keeps a moment from running away.” -Eudora Welty</h3>


<!-- <p>Find me in app/views/pictures/new.html.erb</p> -->
<div id="div-space"></div>
<div>
  <%= form_for [@user, @picture] do |f|%>
  <%= f.label :url, 'Upload Photo' %>
  <%= f.file_field :url, placeholder: 'Upload Picture' %>
<div id="div-space"></div>
  <%= f.label :caption, 'Caption' %>
<div id="div-space2"></div>
  <%= f.text_field :caption, placeholder: 'Write a caption' %>
  <!-- <%= f.label :tag, 'tag' %> -->
  <!-- <%= f.text_field :tag, placeholder: 'Write a tag' %> -->
  <%= f.submit 'Upload' %>



  <% end%>
</div>

app/views/pictures/show.html.erb
<h1>Pictures#show</h1>
<p>Find me in app/views/pictures/show.html.erb</p>

app/views/pictures/update.html.erb
<h1>Pictures#update</h1>
<p>Find me in app/views/pictures/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users Edit</h1>

<!-- #make form -->


  <%= form_for @user do |f| %>
<div>
  <div>
    <br>
    Enter your username here:
    <br>
    <%= f.text_field :name, placeholder:"Username.." %>
  </div>

  <div>
    <br>
    Enter your tagline here
    <br>
    <%= f.text_field :tagline, placeholder: "Tagline.." %>
    <% f.submit 'Edit Tagline' %>
    <% @user.tagline %>
  </div>

  <div>
    <br>
    Enter your bio here:
    <br>
    <%= f.text_field :bio, placeholder: "Bio.." %>
    <% f.submit 'Edit Bio' %>
    <% @user.bio %>
  </div>

    <%= f.submit 'Update' %>
    <% end %>
</div>

app/views/users/index.html.erb
<h1>Collective Collaboration</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Create An Account</h1>

<field>

<%= form_for @user do |f| %>
<div>
  <%= f.text_field :name, placeholder:"Name" %>

</div>

<div>
  <%= f.email_field :email, placeholder:"Email" %>
</div>

<div>
  <%= f.password_field :password, placeholder: "Password" %>
</div>

<div>
  <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %>
</div>

<div>
  <%= f.submit 'Create Account' %>
</div>


</field>



<% end %>

app/views/users/show.html.erb
<!-- <h1>Show view 2 </h1> -->

<div class="middle">
  <%= @user.pic_url %>
  <br>
  <p class="boldfont"><%= @user.name%></p>
  <br>
  <p class="tagline"><%= @user.tagline %></p>
  <br>
  <p class="bio"><%= @user.bio %></p>
  <br>
  <p class="edit"><%= link_to 'Edit', edit_user_path %></p>
</div>

<div class="middle">
  <br>
  <%= link_to 'Add Picture', new_user_picture_path(@user)%>
  <br>
</div>
<div class="middle">
  <% @user.pictures.reverse.each do |pic| %>
<div class="col-md-4">
  <%= image_tag(pic.url) %>
  <h3 class="edit-delete caption-style"><%= pic.caption %></h3>
  <!-- <div class="edit-delete"> -->
    <%= link_to 'Edit', edit_user_picture_path(@user.id, pic), class: 'edit-delete ed-size'%>
    <%= link_to 'Delete', user_picture_path(@user.id, pic), method: 'Delete', data: {confirm: 'Are you sure?'}, class: 'edit-delete ed-size' %>
  <!-- </div> -->
</div>

  <% end %>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<%= @user.tagline %>